### ISSUE TITLE
No release for 1.0 x64 (ie: linux)

### ISSUE THREAD

**Issue by linuxgurugamer** [rbray89/ActiveTextureManagement#23]
Not sure if needed, but I noticed that (since I run Linux), there is no release for the 64 bit version for 1.0

**Comment by sergioberg** [comment]
And seems there is problem: ATM crashes few times after install new mod(if many mods already installed)

**Comment by blnk2007** [comment]
I'm running better on Ubuntu and KSP 64 bit without ATM. I tried ATM x86

**Comment by Ristellise** [comment]
why linux pepes need ATM? you just can get more ram.... (linux people has 64bit and they are trying to reduce their memory strange..)

**Comment by blnk2007** [comment]
Even Linux 64bit ksp doesn't utilize all the memory with 16gb of ram ksp
was crashing around 7 or 8 gb despite plenty of ram left.

**Comment by Ristellise** [comment]
i guess ypu have too many mods then....
